{
 "title": "Go Micro",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(micro_uptime, name)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(micro_uptime{name=\"$service\"}, version)"
   },
   {
    "name": "id",
    "label": "ID",
    "query": "label_values(micro_uptime{name=\"$service\"},id)"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,10m,30m,1h" },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "micro_uptime{name=\"$service\",version=\"$version\",id=\"$id\"}"
    }
   ]
  },
  { "title": "Handle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Handle QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(micro_handle_total{name=\"$service\",version=\"$version\",id=\"$id\"}[$interval])",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(micro_handle_duration_seconds_bucket{name=\"$service\", version=\"$version\", id=\"$id\"}[$interval])) by (le))",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Subscribe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Subscribe QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(micro_subscribe_total{name=\"$service\"}[$interval])",
     "legendFormat": "{{id}} - {{version}}"
    }
   ]
  },
  {
   "title": "Quantile of subscribe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(micro_subscribe_duration_seconds_bucket{name=~\"$service\"}[$interval])) by (le))",
     "legendFormat": " "
    }
   ]
  }
 ]
}